// Created by TraceCompiler 1.3.1
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __GSCONNSETTINGSPLUGINMODELTRACES_H__
#define __GSCONNSETTINGSPLUGINMODELTRACES_H__

#define KOstTraceComponentID 0x200255b8

#define CSP_LOADSETTINGSL_USAGE_OF_NEW_WLAN_PARAM_TRACE 0x30001
#define CSP_SAVESETTINGSL_USAGE_OF_NEW_WLAN_PARAM_TRACE 0x30004
#define CSP_LOADSETTINGSL_CELLULAR_DATA_USAGE_VISITOR_PARAM_TRACE 0x30007
#define CSP_LOADSETTINGSL_CELLULAR_DATA_USAGE_HOME_PARAM_TRACE 0x30008
#define CSP_SAVESETTINGSL_CELLULAR_DATA_USAGE_VISITOR_PARAM_TRACE 0x30009
#define CSP_SAVESETTINGSL_CELLULAR_DATA_USAGE_HOME_PARAM_TRACE 0x3000a


#endif

// End of file

