// Created by TraceCompiler1.1.6
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __GSCONNSETTINGSPLUGINMODELTRACES_H__
#define __GSCONNSETTINGSPLUGINMODELTRACES_H__

#define KOstTraceComponentID 0x200255b8

#define CSP_LOADSETTINGSL_USAGE_OF_NEW_WLAN_PARAM_TRACE 0x30002
#define CSP_LOADSETTINGSL_FORCED_ROAMING_PARAM_TRACE 0x30003
#define CSP_LOADSETTINGSL_SEAMLESSNESS_VISITOR_PARAM_TRACE 0x30004
#define CSP_LOADSETTINGSL_SEAMLESSNESS_HOME_PARAM_TRACE 0x30005
#define CSP_SAVESETTINGSL_USAGE_OF_NEW_WLAN_PARAM_TRACE 0x30007
#define CSP_SAVESETTINGSL_FORCED_ROAMING_PARAM_TRACE 0x30008
#define CSP_SAVESETTINGSL_SEAMLESSNESS_VISITOR_PARAM_TRACE 0x30009
#define CSP_SAVESETTINGSL_SEAMLESSNESS_HOME_PARAM_TRACE 0x3000a


#endif

// End of file

